[package]
name = "xtask"
description = "cargo xtask: build, install and package"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
nih_plug_xtask = { git = "https://github.com/robbert-vdh/nih-plug.git" }
anyhow = "1"
deviceout-update = { path = "../crates/deviceout-update" }
serde_json = "1"
ureq = "3.4.0"
